server:
  port: 9191

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: prodcat
          uri: lb://PRODCAT
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=1   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
